###

POST  http://127.0.0.1:8080/chat/d73f0d3c-6a8b-4a22-b8a1-399d4fba9a2b/add
Content-Type: application/json

{
  "username": "Jonny",
  "text": "Hello!"
}


###

POST  http://127.0.0.1:8080/chat/62435507ba52718b33ab6094/add
Content-Type: application/json

{
  "username": "Tommy",
  "text": "Hello!"
}